(env (_ (flags (:standard -w @a-42-40-44-70-45-41))))

(library
 (name zkapps_rollup)
 (libraries
  ;; opam libraries
  core_kernel
  transaction_snark
  staged_ledger_diff
  )
 (inline_tests)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_deriving.show ppx_deriving_snarky ppx_snarky ppx_mina ppx_version ppx_jane ppx_compare h_list.ppx))
 (modules zkapps_rollup zkapps_rollup_intf rule_bridge_finalize_deposit bridge_state outer_rules inner_rules rule_commit rule_action_witness rule_inner_sync ase rollup_state folder zeko_util compile_simple_intf)
 (modules_without_implementation zkapps_rollup_intf)
 )
