(executable
 (name cli)
 (libraries
  zeko_constants
  fileutils
  da_layer
  mina_transaction
  mina_lib
  mina_ledger
  archive_lib
  core_unix.command_unix
  yojson
  cohttp
  cohttp-async
  websocket-async
  async_kernel
  gql_client
  is_compile_simple_real_real)
 (preprocess
  (pps ppx_jane ppx_mina))
 (modules cli archive_relay))
