(executable
 (name cli)
 (libraries
  zeko_prover
  ;; mina ;;
  mina_base
  cli_lib
  signature_lib
  ;; opam ;;
  async
  core_unix.command_unix
  is_compile_simple_real_real)
 (preprocess
  (pps ppx_jane ppx_mina))
 (modules cli))

(executable
 (name cli_fake)
 (libraries
  zeko_prover
  is_compile_simple_real_fake
  ;; mina ;;
  mina_base
  cli_lib
  signature_lib
  ;; opam ;;
  async
  core_unix.command_unix)
 (preprocess
  (pps ppx_jane ppx_mina))
 (modules cli_fake))
