(executable
 (name compile_circuits)
 (libraries zeko_circuits)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_deriving.show ppx_deriving_snarky ppx_snarky ppx_mina ppx_version ppx_jane ppx_compare h_list.ppx))
 (modules compile_circuits)
 )

(executable
 (name basic_prove_test)
 (libraries zeko_circuits compile_simple_fake)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_deriving.show ppx_deriving_snarky ppx_snarky ppx_mina ppx_version ppx_jane ppx_compare h_list.ppx))
 (modules basic_prove_test account_set_data)
 )

(executable
 (name transfers)
 (libraries zeko_circuits graphql_lib)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_deriving.show ppx_deriving_snarky ppx_snarky ppx_mina ppx_version ppx_jane ppx_compare h_list.ppx))
 (modules transfers)
 )
