(env
 (_
  (flags
   (:standard -w @a-42-40-44-70-45-41))))

(executable
 (name compile_circuits)
 (libraries zeko_circuits compile_simple compile_simple_real)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps
   ppx_deriving.show
   ppx_deriving_snarky
   ppx_snarky
   ppx_mina
   ppx_version
   ppx_jane
   ppx_compare
   h_list.ppx))
 (modules compile_circuits))

(library
 (name account_set_data)
 (libraries zeko_circuits mina_base)
 (preprocess
  (pps
   ppx_deriving.show
   ppx_deriving_snarky
   ppx_snarky
   ppx_mina
   ppx_version
   ppx_jane
   ppx_compare
   h_list.ppx))
 (modules account_set_data))

(executable
 (name test_all_fake)
 (libraries
  zeko_circuits
  compile_simple_fake
  account_set_data
  zeko_constants)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps
   ppx_deriving.show
   ppx_deriving_snarky
   ppx_snarky
   ppx_mina
   ppx_version
   ppx_jane
   ppx_compare
   h_list.ppx))
 (modules test_all_fake))

(executable
 (name test_all_real)
 (libraries
  zeko_circuits
  compile_simple_real
  sequencer_lib
  is_compile_simple_real_real
  account_set_data
  zeko_constants)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps
   ppx_deriving.show
   ppx_deriving_snarky
   ppx_snarky
   ppx_mina
   ppx_version
   ppx_jane
   ppx_compare
   h_list.ppx))
 (modules test_all_real))

(executable
 (name ethereum_bridge_vectors)
 (libraries
  zeko_circuits
  compile_simple_fake
  sequencer_lib
  is_compile_simple_real_fake
  zeko_constants)
 (preprocess
 (pps ppx_jane))
 (modules ethereum_bridge_vectors))

(executable
 (name asset_registry_vectors)
 (libraries zeko_circuits compile_simple_fake zeko_constants)
 (preprocess
  (pps ppx_jane))
 (modules asset_registry_vectors))

(executable
 (name test_pause_fake)
 (libraries zeko_circuits compile_simple_fake)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_deriving.show ppx_jane ppx_compare))
 (modules test_pause_fake))

(executable
 (name test_pause_real)
 (libraries zeko_circuits compile_simple_real)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_deriving.show ppx_jane ppx_compare))
 (modules test_pause_real))

(executable
 (name test_zkapp_fake)
 (libraries zeko_circuits compile_simple_fake account_set_data)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_deriving.show ppx_jane ppx_compare))
 (modules test_zkapp_fake))

(executable
 (name test_zkapp_real)
 (libraries zeko_circuits compile_simple_real account_set_data)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_deriving.show ppx_jane ppx_compare))
 (modules test_zkapp_real))

(executable
 (name transfers)
 (libraries zeko_circuits graphql_lib)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps
   ppx_deriving.show
   ppx_deriving_snarky
   ppx_snarky
   ppx_mina
   ppx_version
   ppx_jane
   ppx_compare
   h_list.ppx))
 (modules transfers))
