(library
 (name test_spec)
 (libraries sequencer_lib)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules test_spec))

(executable
 (name sequencer_test)
 (libraries
  sequencer_lib
  is_compile_simple_real_real
  initialize_state
  test_spec)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules sequencer_test))

(executable
 (name sequencer_test_fake)
 (libraries
  sequencer_lib
  is_compile_simple_real_fake
  initialize_state
  test_spec)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules sequencer_test_fake))

(executable
 (name testing)
 (libraries
  sequencer_lib
  is_compile_simple_real_fake
  initialize_state
  test_spec)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules testing))

(executable
 (name relational_db_test)
 (libraries sequencer_lib is_compile_simple_real_real)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules relational_db_test))

(executable
 (name persisted_merger_test)
 (libraries
  parallel_merger
  fields_derivers.graphql
  fields_derivers_zkapps
  yojson)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules persisted_merger_test))
