(library
 (name test_spec)
 (libraries sequencer_lib)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules test_spec))

(executable
 (name sequencer_test)
 (libraries
  sequencer_lib
  is_compile_simple_real_real
  initialize_state
  test_spec)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules sequencer_test))

(executable
 (name sequencer_test_fake)
 (libraries
  sequencer_lib
  is_compile_simple_real_fake
  initialize_state
  test_spec)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules sequencer_test_fake))

(executable
 (name relational_db_test)
 (libraries sequencer_lib is_compile_simple_real_real)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules relational_db_test))

(executable
 (name persisted_merger_test)
 (libraries
  parallel_merger
  fields_derivers.graphql
  fields_derivers_zkapps
  yojson)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules persisted_merger_test))

(executable
 (name commit_schedule_test)
 (libraries sequencer_lib is_compile_simple_real_fake)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules commit_schedule_test))

(executable
 (name settlement_finality_test)
 (libraries sequencer_lib is_compile_simple_real_fake)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules settlement_finality_test))

(executable
 (name slot_duration_test)
 (libraries utils core_kernel mina_numbers is_compile_simple_real_fake)
 (modules slot_duration_test))

(executable
 (name imt_benchmark)
 (libraries indexed_merkle_tree yojson)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules imt_benchmark))

(executable
 (name preverify_test)
 (libraries
  sequencer_lib
  is_compile_simple_real_real
  consensus
  staged_ledger_diff
  genesis_ledger
  mina_state
  cli_lib)
 (preprocess
  (pps ppx_let ppx_jane ppx_mina))
 (modules preverify_test))
