# Builds and tests Zeko in CI using the exported opam toolchain.
---
name: CI

on:
  push:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-test:
    name: "Build & Test"
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: 🧰 Setup Zeko CI
        uses: ./.github/actions/setup-zeko-ci
        timeout-minutes: 20
        with:
          opam-cache-key: zeko_opam_dependencies-${{ hashFiles('./opam.export') }}
          build-cache-key: zeko_build-${{ hashFiles('./opam.export') }}
      # Build!
      - name: 📦 Build zeko packages
        run: |
          opam exec -- dune build --profile=devnet src/app/zeko/sequencer
          opam exec -- dune build --profile=devnet src/app/zeko/sequencer/explorer
          opam exec -- dune build --profile=devnet src/app/zeko/da_layer
          opam exec -- dune build --profile=devnet src/app/zeko/signer
      - name: 🧪 Run sequencer tests
        run: ./src/app/zeko/sequencer/tests/run-sequencer-test.sh real 1
